columns:
  - id: int
  - unit_id: int
  - cycle: int
  - op_setting_1: float
  - op_setting_2: float
  - op_setting_3: float
  - sensor_1: float
  - sensor_2: float
  - sensor_3: float
  - sensor_4: float
  - sensor_5: float
  - sensor_6: float
  - sensor_7: float
  - sensor_8: float
  - sensor_9: float
  - sensor_10: float
  - sensor_11: float
  - sensor_12: float
  - sensor_13: float
  - sensor_14: float
  - sensor_15: float
  - sensor_16: float
  - sensor_17: float
  - sensor_18: float
  - sensor_19: float
  - sensor_20: float
  - sensor_21: float

numerical_columns:
  - id
  - unit_id
  - cycle
  - op_setting_1
  - op_setting_2
  - op_setting_3
  - sensor_1
  - sensor_2
  - sensor_3
  - sensor_4
  - sensor_5
  - sensor_6
  - sensor_7
  - sensor_8
  - sensor_9
  - sensor_10
  - sensor_11
  - sensor_12
  - sensor_13
  - sensor_14
  - sensor_15
  - sensor_16
  - sensor_17
  - sensor_18
  - sensor_19
  - sensor_20
  - sensor_21

categorical_columns:

drop_columns:
  - unit_id
  - op_setting_1
  - op_setting_2
  - op_setting_3
  - sensor_1
  - sensor_5
  - sensor_6
  - sensor_8
  - sensor_10
  - sensor_13
  - sensor_16
  - sensor_18
  - sensor_19